### PR TITLE
dxx-rebirth - Update to e3faab0899bc86184fdd67568ccc4f237c5f6807

### PR DESCRIPTION
**Pull request by jcotton42**
### New Engine Package Submissions

* [x] Have you followed the instructions in the build documentation?
* [x] Have you run the build locally and ensured the package allowed you to launch and play the Steam game?
* [x] Have you updated the packages.json file?
* [x] Have you ensured that there is not already a pull request or active engine package for the one you are adding?

I'm still waiting for the engine to build locally. I started the build on my Steam Deck, and it didn't realize it would involve building gcc, so I wanted to get this check going in the PR workflow. But since I'm just bumping the commit used, and no changes to dependencies have been made since the last package, it *should* be fine.

I'll come back and update this when the build finishes locally.

### CODE REVIEW

**Review by d10sfan — CHANGES_REQUESTED** [review]
@jcotton42 Thanks for the heads up and help with the update!

For this, can you fix the commit author? Currently it says "steam deck user". You should be able to follow steps similar to this: https://stackoverflow.com/questions/3042437/how-to-change-the-commit-author-for-a-single-commit

If that doesn't work out, let me know and I might be able to fix it on my side.

**Comment by jcotton42** [comment]
> @jcotton42 Thanks for the heads up and help with the update!
> 
> For this, can you fix the commit author? Currently it says "steam deck user". You should be able to follow steps similar to this: https://stackoverflow.com/questions/3042437/how-to-change-the-commit-author-for-a-single-commit
> 
> If that doesn't work out, let me know and I might be able to fix it on my side.

Good catch, I had forgotten to configure user.name/user.email in my git config. Should be all sorted now.

**Comment by jcotton42** [comment]
By the way, what's up with `"controllerNotSupported": true` in the engine JSON? Rebirth natively supports joysticks, is that referring to something else?

**Comment by d10sfan** [comment]
> By the way, what's up with `"controllerNotSupported": true` in the engine JSON? Rebirth natively supports joysticks, is that referring to something else?

That is referring to controllers like the steam deck, xbox controller, ps controller, steam controller, etc. If it is supported and out of the box, that can be changed. If it's supported but needs manual steps to get it to work, then there's another status for that as well.

**Comment by jcotton42** [comment]
Ah. They should just work (as in Rebirth should natively see it as a game pad), I can test after the GCC build stops holding my deck hostage. 😆

**Comment by d10sfan** [comment]
> Ah. They should just work (as in Rebirth should natively see it as a game pad), I can test after the GCC build stops holding my deck hostage. laughing

I just tried it with my xbox one controller and it kind of works but not all that well. I have to click enable joystick and then the menu does not appear to work with the controller (have to use keyboard or mouse). When in-game, the right stick works for moving the camera around and the weapon buttons work, but I can't figure out how to move, i assumed it'd be the left stick, but nothing happens.

**Comment by jcotton42** [comment]
So I've made the packages locally. How do I go about testing them fully? I see I can make a user-packages.json https://github.com/luxtorpeda-dev/luxtorpeda/issues/65, but it's not clear if I can tell that to just pull an archive off the local filesystem, instead of pulling from the internet.

**Comment by d10sfan** [comment]
> So I've made the packages locally. How do I go about testing them fully? I see I can make a user-packages.json [luxtorpeda-dev/luxtorpeda#65](https://github.com/luxtorpeda-dev/luxtorpeda/issues/65), but it's not clear if I can tell that to just pull an archive off the local filesystem, instead of pulling from the internet.

If you have a user-package for the steam app id and have an empty downloads array, that should override the downloading from occuring. Then you can manually copy the changes. Another option would be to edit the archive inside ~/.cache/luxtorpeda/<app_id>

**Comment by jcotton42** [comment]
I think I got it to work on my side?

I copied the tarball to ~/.cache/luxorpeda/<app id>, and luxor didn't show that it was downloading it from anywhere, so I presume it just used the local copy?

**Comment by d10sfan** [comment]
> I think I got it to work on my side?
> 
> I copied the tarball to ~/.cache/luxorpeda/, and luxor didn't show that it was downloading it from anywhere, so I presume it just used the local copy?

Right, that'd make sense.

**Review by d10sfan — APPROVED** [review]

**Comment by d10sfan** [comment]
@jcotton42 

Great, I've approved this and will merge. If you end up spending some time on the controller pieces, feel free to create another PR!

**Pull request merged**
