### PR TITLE
Godot 4.3

### PR DESCRIPTION
**Pull request by Ryhon0**
This PR adds Godot 4.3 as an engine to be used by the [Road to Vostok Demo](https://steamdb.info/app/2141300).  
There isn't enough documentation for me to figure out how to run the built package so I wasn't able to test the game.  
I also don't know what's the process for adding a new version of the engine, so I can make changes if needed.

### New Engine Package Submissions

* [x] Have you followed the instructions in the build documentation?
* [ ] Have you run the build locally and ensured the package allowed you to launch and play the Steam game?   
* [x] Have you updated the packages.json file?
* [x] Have you ensured that there is not already a pull request or active engine package for the one you are adding?

### CODE REVIEW

**Review by d10sfan — CHANGES_REQUESTED** [review]
For this itd be easier to download the Godot binaries like the original Godot engine does. 

That could then be done in the same Godot folder for the script assets with a script to launch that particular game.

The downloads array from packages json file is how it'll download the proper one.

In terms of testing usually what I do is edit the config to disable fetching the packages data then copy my changes into the cache folder.

**Comment by Ryhon0** [comment]
The Cruelty Squad downloads the editor binary, which will reduce the performance and will run editor specific code. There's no official way to get a specific export template binary instead, they're all in a 1GB zip, so the binary would have to be uploaded somewhere and using the godot package will needlessly download the 3.4 version of the editor

**Comment by d10sfan** [comment]
> The Cruelty Squad downloads the editor binary, which will reduce the performance and will run editor specific code. There's no official way to get a specific export template binary instead, they're all in a 1GB zip, so the binary would have to be uploaded somewhere and using the godot package will needlessly download the 3.4 version of the editor

AH I see now, I forgot that the godot engine actually builds godot.

So what you are doing makes sense then. You'l want to have a godot 4-3 asset script for running this particular game, since your script is excepting certain pcks.

For seeing if this builds, edit the engine godot file which will then trigger the build to complete and it'll upload an artifact. Then you can use that for your local testing.

**Comment by d10sfan** [comment]
Thanks for the great work so far here. I've done a minor change and then I'm going to merge this. Did a quick test and it loads the game well. Thanks for the idea.

**Pull request merged**
