### PR TITLE
unreal-gold - Switch to 32-bit

### PR DESCRIPTION
**Pull request by d10sfan**
Having issues finding openal:

```
Failed to load ALAudio: Can't find file for package ALAudio..
Failed to load "Class ALAudio.ALAudioSubsystem": Can't find file for package ALAudio..
Can't find file for package ALAudio.
appError called:
Can't find file for package ALAudio.
Executing UObject::StaticShutdownAfterError
SDL2: Executing USDL2Client::ShutdownAfterError
UOpenGLRenderDevice::ShutdownAfterError
```

That should be included with the steam runtime, so check if 32-bit exists, and maybe soft-link in like other engines.

### CODE REVIEW

**Comment by daemonspudguy** [comment]
I can explain it. The compatibility-tools tarball in the help file includes all of the libraries you need. One of them is libxmp.so.4

**Comment by daemonspudguy** [comment]
It's a dependency of the OpenAL library used here. If you don't have it, it decides it can't find the library.

**Comment by daemonspudguy** [comment]
So just use the compatibility tarball in the Help folder.

**Comment by d10sfan** [comment]
@daemonspudguy The openal wasn't needed for 64-bit, which pointed to something in the runtime.

I will look into that archive, although it's trickier than normal, since the tar command from steam runtime does not have bz2 support, so if I want to use that I will need to provide the archive tools in the engine package.

**Comment by daemonspudguy** [comment]
The specific file needed by Unreal for libxmp is called libxmp.so.4, at least according to my testing.

**Comment by daemonspudguy** [comment]
At least in my testing, you need the libxmp file to be named libxmp.so.4.

**Comment by daemonspudguy** [comment]
@d10sfan the libxmp.so.4 file also goes in the libs folder, as that's where Unreal Gold looks for it.

**Comment by d10sfan** [comment]
@daemonspudguy I am aware, I will take a look when I have a chance.

**Comment by daemonspudguy** [comment]
@d10sfan any news?

**Comment by d10sfan** [comment]
@daemonspudguy As I mentioned, I will look into it when I have a chance. I'll comment here when there's an update.

**Comment by d10sfan** [comment]
@daemonspudguy It should work now. Note that you will need to do a full uninstall and then re-install. That'll mean uninstalling the game from steam and then clearing out the Unreal Gold directory of any leftover files.

**Comment by daemonspudguy** [comment]
sounds good.

**Pull request merged**
